export function render(parentElement?: any, routes?: any[], initialDelay?: number): any;
import { html } from './src/rendering/index.js';
import { List } from './src/rendering/index.js';
import { getRef } from './src/rendering/index.js';
import { reactive } from './src/rendering/index.js';
import { css } from './src/rendering/index.js';
import { useEffect } from './src/store/index.js';
import { useState } from './src/store/index.js';
import { createStore } from './src/store/index.js';
import { useStore } from './src/store/index.js';
import { radio } from './src/store/index.js';
export function useRouter(): any;
export function getRootElement(): any;
import { useSuspense } from './src/hooks/index.js';
import { setConfig } from './src/fetch/index.js';
import { setBearerToken } from './src/fetch/index.js';
import { GET } from './src/fetch/index.js';
import { POST } from './src/fetch/index.js';
import { PUT } from './src/fetch/index.js';
import { PATCH } from './src/fetch/index.js';
import { DELETE } from './src/fetch/index.js';
export { html, List, getRef, reactive, css, useEffect, useState, createStore, useStore, radio, useSuspense, setConfig, setBearerToken, GET, POST, PUT, PATCH, DELETE };
